version: 2
updates:
  # gh-pages branch
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      actions-dependencies:
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    groups:
      pnpm-dependencies:
        patterns:
          - '*'

  # Drupal branch
  - package-ecosystem: npm
    directory: /app/Drupal/nts_theme
    schedule:
      interval: monthly
    target-branch: drupal
    groups:
      theme-dependencies:
        patterns:
          - '*'
