version: 3

env:
  PHP_BIN: '{{.PHP_BIN | default "$(which php)"}}'
  NODE_BIN: '{{.NODE_BIN | default "$(which node)"}}'
  PNPM_BIN: '{{.PNPM_BIN | default "$(which pnpm)"}}'
  COMPOSER_BIN: '{{.COMPOSER_BIN | default "$(which composer)"}}'

vars:
  CONFIG_DIR: '{{.TASKFILE_DIR}}/config/utils'
  NODEJS_BIN_DIR: '{{.TASKFILE_DIR}}/node_modules/.bin'
  COMPOSER_BIN_DIR: '{{.TASKFILE_DIR}}/vendor/bin'

tasks:
  default:
    desc: 'List all commands.'
    cmd: 'task -l'

  # Utils:

  composer:
    desc: 'Run `composer` command.'
    cmd: '{{.PHP_BIN}} {{.COMPOSER_BIN}} {{.CLI_ARGS}} --ansi'
    internal: true
    silent: true

  pnpm:
    desc: 'Run `pnpm` command.'
    cmd: '{{.PNPM_BIN}} {{.CLI_ARGS}}'
    internal: true
    silent: true

  artisan:
    desc: 'Run `artisan` command.'
    cmd: '{{.PHP_BIN}} artisan {{.CLI_ARGS}} --ansi'
    aliases:
      - art
    internal: true
    silent: true

  artisan:test:
    desc: 'Run `artisan test` command.'
    aliases:
      - a:t
    cmds:
      - task: artisan
        vars: { CLI_ARGS: 'test -c {{.CONFIG_DIR}}/phpunit.xml --parallel {{.CLI_ARGS}}' }
        silent: true

  pint:
    desc: 'Run `pint` command.'
    cmd:
      '{{.PHP_BIN}} {{.COMPOSER_BIN_DIR}}/pint
      --config={{.CONFIG_DIR}}/pint.json
      {{.CLI_ARGS}} --ansi'
    silent: true

  phpstan:
    desc: 'Run `phpstan` command.'
    aliases:
      - php:stan
    cmd:
      '{{.PHP_BIN}} {{.COMPOSER_BIN_DIR}}/phpstan
      --configuration={{.CONFIG_DIR}}/phpstan.neon {{.CLI_ARGS}} --ansi'
    silent: true

  rector:
    desc: 'Run `rector` command.'
    cmd:
      '{{.PHP_BIN}} {{.COMPOSER_BIN_DIR}}/rector {{.CLI_ARGS}}
      --config={{.CONFIG_DIR}}/rector.php --ansi'
    aliases:
      - r
    silent: true

  prettier:
    desc: 'Run `prettier` command.'
    cmd:
      '{{.NODEJS_BIN_DIR}}/prettier {{.CLI_ARGS}}
      --config={{.CONFIG_DIR}}/.prettierrc.json
      --ignore-path={{.CONFIG_DIR}}/.prettierignore
      --cache --cache-location=var/cache/prettier/prettier.cache'
    silent: true

  peck:
    desc: 'Run `peck` command.'
    cmd:
      '{{.PHP_BIN}} {{.COMPOSER_BIN_DIR}}/peck
      --config={{.CONFIG_DIR}}/peck.json {{.CLI_ARGS}} --ansi'
    silent: true

  pest:
    desc: 'Run `pest` command.'
    cmd:
      '{{.PHP_BIN}} {{.COMPOSER_BIN_DIR}}/pest
      --configuration={{.CONFIG_DIR}}/phpunit.xml
      {{.CLI_ARGS}} --colors=always'
    silent: true

  # Work commands:

  cache:clear:
    desc: 'Clear all Laravel caches'
    aliases:
      - cc
      - cr
    cmds:
      - task: artisan
        vars: { CLI_ARGS: 'optimize:clear' }

  install:
    desc: 'Install project'
    aliases:
      - i
    cmds:
      - task: composer
        vars: { CLI_ARGS: 'install' }
      - task: pnpm
        vars: { CLI_ARGS: 'install' }
      - task: artisan
        vars: { CLI_ARGS: 'key:generate' }
      - task: db:fresh

  update:
    desc: 'Updates project dependencies withing constraints.'
    prompt: |
      This command can break website. Do it independently without any other active changes.
      Make sure you have a backup. Never run it on production.
    aliases:
      - u
    cmds:
      - task: composer
        vars: { CLI_ARGS: 'u -W' }
      - task: pnpm
        vars: { CLI_ARGS: 'up --save --latest' }

  deploy:
    desc: 'Deploy project'
    aliases:
      - d
    cmds:
      - task: artisan
        vars: { CLI_ARGS: 'down' }
      - task: composer
        vars: { CLI_ARGS: 'i --no-dev' }
      - task: artisan
        vars: { CLI_ARGS: 'migrate --force' }
      - task: cache:clear
      - task: artisan
        vars: { CLI_ARGS: 'optimize' }
      - task: docs:generate
      - task: artisan
        vars: { CLI_ARGS: 'up' }

  db:fresh:
    desc: 'Drop all tables and re-run all migrations'
    aliases:
      - m:f
      - db:f
      - db:rf
      - db:refresh
    cmds:
      - task: artisan
        vars: { CLI_ARGS: 'migrate:fresh --seed --force' }

  db:schema:dump:
    desc: 'Dump the given db schema and delete all existing migration'
    aliases:
      - db:s:d
    cmds:
      - task: artisan
        vars: { CLI_ARGS: 'schema:dump --prune' }

  docs:generate:
    desc: 'Generate docs with scribe.'
    aliases:
      - docs
    cmds:
      - task: artisan
        vars: { CLI_ARGS: 'scribe:generate --scribe-dir=var/.scribe-v1 --config scribe-v1' }

  # Linters:

  lint:
    desc: 'Run all linters and validators.'
    aliases:
      - l
    cmds:
      - defer: { task: lint:prettier }
      - defer: { task: lint:rector }
      - defer: { task: lint:phpstan }
      - defer: { task: lint:pint }
      - defer: { task: lint:composer }
      - defer: { task: lint:commit }
      - defer: { task: lint:branch }

  lint:branch:
    desc: 'Validates the current git branch name.'
    aliases:
      - l:b
      - lint:b
    cmds:
      - task: pnpm
        vars: { CLI_ARGS: 'validate-branch-name -v' }
      - task: pnpm
        vars: { CLI_ARGS: 'validate-branch-name' }

  lint:commit:
    desc: 'Run commit message validation using commitlint.'
    aliases:
      - l:cmt
      - l:commit
      - lint:cmt
    cmds:
      - task: pnpm
        vars: { CLI_ARGS: 'commitlint -v' }
      - task: pnpm
        vars: { CLI_ARGS: 'commitlint --from=HEAD~1 --to=HEAD' }

  lint:composer:
    desc: 'Validates composer.json and platform requirements.'
    aliases:
      - l:co
      - l:composer
      - lint:co
    cmds:
      - task: composer
        vars: { CLI_ARGS: '-V' }
      - task: composer
        vars: { CLI_ARGS: 'validate --no-check-version --no-check-publish --strict' }
      - task: composer
        vars: { CLI_ARGS: 'check-platform-req' }

  lint:pint:
    desc: 'Validate PHP for code style.'
    aliases:
      - l:p
      - l:pint
      - lint:p
    cmds:
      - task: pint
        vars: { CLI_ARGS: '-V' }
      - task: pint
        vars: { CLI_ARGS: '. --test {{.CLI_ARGS}}' }

  lint:phpstan:
    desc: 'Analyze PHP code for bugs and errors.'
    aliases:
      - l:s
      - l:stan
      - l:phpstan
      - lint:s
      - lint:stan
    cmds:
      - task: phpstan
        vars: { CLI_ARGS: '-V' }
      - task: phpstan
        vars: { CLI_ARGS: 'analyze {{.CLI_ARGS}}' }

  lint:rector:
    desc: 'Check for Rector refactoring suggestions.'
    aliases:
      - l:r
      - l:rector
      - lint:r
    cmds:
      - task: rector
        vars: { CLI_ARGS: '-V' }
      - task: rector
        vars: { CLI_ARGS: '--dry-run {{.CLI_ARGS}}' }

  lint:peck:
    desc: 'Check pure wording or spelling (grammar) mistakes.'
    aliases:
      - l:peck
    cmds:
      - task: peck
        vars: { CLI_ARGS: '-V' }
      - task: peck

  lint:prettier:
    desc: 'Check code formatting with Prettier.'
    aliases:
      - l:f
      - l:prt
      - l:format
      - l:prettier
      - lint:f
      - lint:prt
      - lint:format
    cmds:
      - task: prettier
        vars: { CLI_ARGS: '-v' }
      - task: prettier
        vars: { CLI_ARGS: '. -c' }

  # Fixing:

  fix:
    desc: 'Run all automated fixers.'
    aliases:
      - f
    cmds:
      - defer: { task: fix:prettier }
      - defer: { task: fix:rector }
      - defer: { task: fix:pint }
      - defer: { task: fix:composer }

  fix:composer:
    desc: 'Fix Composer lock file and dependencies.'
    aliases:
      - f:co
      - f:composer
      - fix:co
    cmds:
      - task: composer
        vars: { CLI_ARGS: '-V' }
      - task: composer
        vars: { CLI_ARGS: 'u --lock --no-scripts --no-plugins --no-autoloader' }
      - task: composer
        vars: { CLI_ARGS: 'bump' }

  fix:pint:
    desc: 'Fix php format issues.'
    aliases:
      - f:p
      - f:pint
      - fix:p
    cmds:
      - task: pint
        vars: { CLI_ARGS: '-V' }
      - task: pint
        vars: { CLI_ARGS: '.' }

  fix:rector:
    desc: 'Apply Rector refactoring suggestions.'
    aliases:
      - f:r
      - f:rector
      - fix:r
    cmds:
      - task: rector
        vars: { CLI_ARGS: '-V' }
      - task: rector
        vars: { CLI_ARGS: '{{.CLI_ARGS}}' }

  fix:prettier:
    desc: 'Auto-fix code formatting with Prettier.'
    aliases:
      - f:f
      - f:prt
      - f:format
      - f:prettier
      - fix:f
      - fix:prt
      - fix:format
    cmds:
      - task: prettier
        vars: { CLI_ARGS: '-v' }
      - task: prettier
        vars: { CLI_ARGS: '. -wl' }

  # Testing:

  test:
    desc: 'Run project test.'
    aliases:
      - t
      - qa
    cmds:
      - defer: { task: test:mutate }
      - defer: { task: test:unit }
      - defer: { task: test:feature }
      - defer: { task: test:coverage }

  test:coverage:
    desc: 'Ensure all methods and properties have type declarations.'
    aliases:
      - t:c
      - t:coverage
      - qa:c
      - qa:coverage
      - test:c
    cmds:
      - task: pest
        vars: { CLI_ARGS: '--version' }
      - task: pest
        vars: { CLI_ARGS: '--type-coverage --compact --min=100 {{.CLI_ARGS}}' }

  test:feature:
    desc: 'Run feature test.'
    aliases:
      - t:f
      - t:feature
      - qa:f
      - qa:feature
      - test:f
    cmds:
      - task: pest
        vars: { CLI_ARGS: '--version' }
      - task: artisan:test
        vars: { CLI_ARGS: '--testsuite=Feature {{.CLI_ARGS}}' }

  test:unit:
    desc: 'Run unit tests.'
    aliases:
      - t:u
      - t:unit
      - qa:u
      - qa:unit
      - test:u
    cmds:
      - task: pest
        vars: { CLI_ARGS: '--version' }
      - task: artisan:test
        vars: { CLI_ARGS: '--testsuite=Unit {{.CLI_ARGS}}' }

  test:mutate:
    desc: 'Run mutate tests.'
    aliases:
      - t:m
      - t:mutate
      - qa:m
      - qa:mutate
      - test:m
    cmds:
      - task: pest
        vars: { CLI_ARGS: '--version' }
      - task: pest
        vars: { CLI_ARGS: '--mutate --covered-only --parallel --min=100 {{.CLI_ARGS}}' }
