version: 3

env:
  PHP_BIN: '{{.PHP_BIN | default "$(which php)"}}'
  NODE_BIN: '{{.NODE_BIN | default "$(which node)"}}'
  PNPM_BIN: '{{.PNPM_BIN | default "$(which pnpm)"}}'
  COMPOSER_BIN: '{{.COMPOSER_BIN | default "$(which composer)"}}'

vars:
  CONFIG_DIR: '{{.TASKFILE_DIR}}/config/utils'
  NODEJS_BIN_DIR: '{{.TASKFILE_DIR}}/node_modules/.bin'
  COMPOSER_BIN_DIR: '{{.TASKFILE_DIR}}/vendor/bin'

tasks:
  default:
    desc: 'List all command.'
    cmd: 'task -l'

  # Utils:

  composer:
    label: 'Composer'
    desc: 'Runs `composer` command.'
    cmd: '{{.PHP_BIN}} {{.COMPOSER_BIN}} {{.CLI_ARGS}} --ansi'
    internal: true
    silent: true

  pnpm:
    label: 'pnpm'
    desc: 'Runs `pnpm` command.'
    cmd: '{{.PNPM_BIN}} {{.CLI_ARGS}}'
    internal: true
    silent: true

  artisan:
    label: 'artisan'
    desc: 'Runs `artisan` command.'
    cmd: '{{.PHP_BIN}} artisan {{.CLI_ARGS}} --ansi'
    internal: true
    silent: true

  artisan:test:
    label: 'artisan test'
    desc: 'Runs `artisan test` command.'
    aliases:
      - a:t
    cmds:
      - task: artisan
        vars:
          { CLI_ARGS: 'test -c {{.CONFIG_DIR}}/phpunit.xml --parallel {{.CLI_ARGS}}' }
        silent: true

  pint:
    label: 'Laravel Pint'
    desc: 'Runs `pint` command.'
    cmd:
      '{{.PHP_BIN}} {{.COMPOSER_BIN_DIR}}/pint
      --config={{.CONFIG_DIR}}/pint.json
      {{.CLI_ARGS}} --ansi'
    silent: true

  phpstan:
    label: 'PHPStan'
    desc: 'Runs `phpstan` command.'
    aliases:
      - php:stan
    cmd:
      '{{.PHP_BIN}} {{.COMPOSER_BIN_DIR}}/phpstan
      --configuration={{.CONFIG_DIR}}/phpstan.neon {{.CLI_ARGS}} --ansi'
    silent: true

  rector:
    label: 'Rector'
    desc: 'Runs `rector` command.'
    cmd:
      '{{.PHP_BIN}} {{.COMPOSER_BIN_DIR}}/rector
      --config={{.CONFIG_DIR}}/rector.php {{.CLI_ARGS}} --ansi'
    silent: true

  prettier:
    label: 'Prettier'
    desc: 'Runs `prettier` command.'
    cmd:
      '{{.NODEJS_BIN_DIR}}/prettier {{.CLI_ARGS}}
      --config={{.CONFIG_DIR}}/.prettierrc.json
      --ignore-path={{.CONFIG_DIR}}/.prettierignore
      --cache --cache-location=var/cache/prettier/prettier.cache'
    silent: true

  pest:
    label: 'Pest'
    desc: 'Runs `pest` command.'
    cmd:
      '{{.PHP_BIN}} {{.COMPOSER_BIN_DIR}}/pest
      --configuration={{.CONFIG_DIR}}/phpunit.xml
      {{.CLI_ARGS}} --colors=always'
    silent: true

  # Work commands:

  cache:clear:
    label: 'Cache clear'
    desc: 'Clear all Laravel caches'
    aliases:
      - cc
      - cr
    cmds:
      - task: artisan
        vars: { CLI_ARGS: 'optimize:clear' }

  update:
    label: 'Update project'
    desc: 'Updates project dependencies withing constraints.'
    prompt: |
      This command can break website. Do it independently without any other active changes.
      Make sure you have a backup. Never run it on production.
    aliases:
      - u
    cmds:
      - task: composer
        vars: { CLI_ARGS: 'u -W' }
      - task: pnpm
        vars: { CLI_ARGS: 'up --save --latest' }

  db:fresh:
    label: 'Refresh database'
    desc: 'Drop all tables and re-run all migrations'
    aliases:
      - m:f
      - db:f
      - db:rf
      - db:refresh
    cmds:
      - task: artisan
        vars: { CLI_ARGS: 'migrate:fresh --seed --force' }

  db:schema:dump:
    label: 'Dum database schema'
    desc: 'Dump the given db schema and delete all existing migration'
    aliases:
      - db:s:d
    cmds:
      - task: artisan
        vars: { CLI_ARGS: 'schema:dump --prune' }

  # Linters:

  lint:
    label: 'Project lint'
    desc: 'Validates project files.'
    aliases:
      - l
    cmds:
      - defer: { task: lint:prettier }
      - defer: { task: lint:rector }
      - defer: { task: lint:phpstan }
      - defer: { task: lint:pint }
      - defer: { task: lint:composer }
      - defer: { task: lint:commit }
      - defer: { task: lint:branch }

  lint:branch:
    label: 'Lint git branch name'
    desc: 'Validates the current git branch name.'
    aliases:
      - l:b
      - lint:b
    cmds:
      - task: pnpm
        vars: { CLI_ARGS: 'validate-branch-name -v' }
      - task: pnpm
        vars: { CLI_ARGS: 'validate-branch-name' }

  lint:commit:
    label: 'Lint last git commits'
    desc: 'Run commit message validation using commitlint.'
    aliases:
      - l:cmt
      - l:commit
      - lint:cmt
    cmds:
      - task: pnpm
        vars: { CLI_ARGS: 'commitlint -v' }
      - task: pnpm
        vars: { CLI_ARGS: 'commitlint --from=HEAD~1 --to=HEAD' }

  lint:composer:
    label: 'Composer validation'
    desc: 'Validates composer.json file and checks platform requirements.'
    aliases:
      - l:co
      - l:composer
      - lint:co
    cmds:
      - task: composer
        vars: { CLI_ARGS: '-V' }
      - task: composer
        vars: { CLI_ARGS: 'validate --no-check-version --no-check-publish --strict' }
      - task: composer
        vars: { CLI_ARGS: 'check-platform-req' }

  lint:pint:
    label: 'Laravel Pint validation'
    desc: 'Validate PHP for code style.'
    aliases:
      - l:p
      - l:pint
      - lint:p
    cmds:
      - task: pint
        vars: { CLI_ARGS: '-V' }
      - task: pint
        vars: { CLI_ARGS: '. --test {{.CLI_ARGS}}' }

  lint:phpstan:
    label: 'PHPStan analyze'
    desc: 'Analyze PHP code for bugs and errors.'
    aliases:
      - l:s
      - l:stan
      - l:phpstan
      - lint:s
      - lint:stan
    cmds:
      - task: phpstan
        vars: { CLI_ARGS: '-V' }
      - task: phpstan
        vars: { CLI_ARGS: 'analyze {{.CLI_ARGS}}' }

  lint:rector:
    label: 'Rector check'
    desc: 'Check Rector issues.'
    aliases:
      - l:r
      - l:rector
      - lint:r
    cmds:
      - task: rector
        vars: { CLI_ARGS: '-V' }
      - task: rector
        vars: { CLI_ARGS: '--dry-run {{.CLI_ARGS}}' }

  lint:prettier:
    label: 'Prettier'
    desc: 'Checks for common format issues with prettier.'
    aliases:
      - l:f
      - l:prt
      - l:format
      - l:prettier
      - lint:f
      - lint:prt
      - lint:format
    cmds:
      - task: prettier
        vars: { CLI_ARGS: '-v' }
      - task: prettier
        vars: { CLI_ARGS: '. -c' }

  # Fixing:

  fix:
    label: 'Fixing found issues'
    desc: 'Trying for automated fixes for found problems.'
    aliases:
      - f
    cmds:
      - defer: { task: fix:prettier }
      - defer: { task: fix:rector }
      - defer: { task: fix:pint }
      - defer: { task: fix:composer }

  fix:composer:
    label: 'Composer fix'
    desc: 'Try to fix composer errors.'
    aliases:
      - f:co
      - f:composer
      - fix:co
    cmds:
      - task: composer
        vars: { CLI_ARGS: 'u --lock --no-scripts --no-plugins --no-autoloader' }
      - task: composer
        vars: { CLI_ARGS: 'bump' }

  fix:pint:
    label: 'Laravel Pint'
    desc: 'Fix php format issues.'
    aliases:
      - f:pint
    cmds:
      - task: pint
        vars: { CLI_ARGS: '.' }

  fix:rector:
    label: 'Rector'
    desc: 'Fix Rector issues.'
    aliases:
      - f:r
      - f:rector
      - fix:r
    cmds:
      - task: rector
        vars: { CLI_ARGS: '{{.CLI_ARGS}}' }

  fix:prettier:
    label: 'Prettier'
    desc: 'Fix format issues.'
    aliases:
      - f:f
      - f:prt
      - f:format
      - f:prettier
      - fix:f
      - fix:prt
      - fix:format
    cmds:
      - task: prettier
        vars: { CLI_ARGS: '. -wl' }

  # Testing:

  test:
    label: 'Project test'
    desc: 'Run project test.'
    aliases:
      - t
      - qa
    cmds:
      - defer: { task: test:mutate }
      - defer: { task: test:unit }
      - defer: { task: test:feature }

  test:feature:
    label: 'Feature test'
    desc: 'Run feature test.'
    aliases:
      - t:f
      - t:feature
      - qa:f
      - qa:feature
      - test:f
    cmds:
      - task: pest
        vars: { CLI_ARGS: '--version' }
      - task: artisan:test
        vars: { CLI_ARGS: '--testsuite=Feature {{.CLI_ARGS}}' }

  test:unit:
    label: 'Unit test'
    desc: 'Run unit tests.'
    aliases:
      - t:u
      - t:unit
      - qa:u
      - qa:unit
      - test:u
    cmds:
      - task: pest
        vars: { CLI_ARGS: '--version' }
      - task: artisan:test
        vars: { CLI_ARGS: '--testsuite=Unit {{.CLI_ARGS}}' }

  test:mutate:
    label: 'Mutate test'
    desc: 'Run mutate tests.'
    aliases:
      - t:m
      - t:mutate
      - qa:m
      - qa:mutate
      - test:m
    cmds:
      - task: pest
        vars: { CLI_ARGS: '--version' }
      - task: pest
        vars: { CLI_ARGS: '--mutate --covered-only --parallel --min=100 {{.CLI_ARGS}}' }
