version: '3'

env:
  PHP_BIN: '{{.PHP_BIN | default "$(which php)"}}'
  NODE_BIN: '{{.NODE_BIN | default "$(which node)"}}'
  PNPM_BIN: '{{.PNPM_BIN | default "$(which pnpm)"}}'
  COMPOSER_BIN: '{{.COMPOSER_BIN | default "$(which composer)"}}'

vars:
  CONFIG_DIR: '{{.TASKFILE_DIR}}/config'
  NODEJS_BIN_DIR: '{{.TASKFILE_DIR}}/node_modules/.bin'
  COMPOSER_BIN_DIR: '{{.TASKFILE_DIR}}/vendor/bin'

tasks:
  default:
    cmd: 'task --list-all'

  composer:
    label: 'Composer'
    desc: 'Runs `composer` command.'
    internal: true
    cmd: '{{.PHP_BIN}} {{.COMPOSER_BIN}} {{.CLI_ARGS}}'

  lint:
    label: 'Project lint'
    desc: 'Validates project files.'
    cmds:
      - task: lint:composer

  lint:composer:
    label: 'Composer validation'
    desc: 'Validates composer.json file and checks platform requirements.'
    cmds:
      - task: composer
        vars: { CLI_ARGS: 'validate --strict --ansi' }
      - task: composer
        vars: { CLI_ARGS: 'check-platform-req --ansi' }