name: '⚙️ Setup environment'
description: 'Setups environment for validation tasks.'

inputs:
  php:
    description: 'PHP version to install'
    required: true
    default: '8.5'

  node:
    description: 'Node.js version to install'
    required: true
    default: '26.x'

  use-php:
    description: 'Whether to install PHP and dependencies'
    required: false
    default: 'false'

  use-node:
    description: 'Whether to install Node.js and dependencies'
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: '📋 Install Task'
      shell: bash
      run: sh -c "$(curl -s --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin > /dev/null 2>&1

    - name: '🐘 Setup PHP ${{ inputs.php }}'
      if: ${{ inputs.use-php == 'true' }}
      uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
      with:
        php-version: ${{ inputs.php }}
        coverage: none
        tools: cs2pr

    - name: '🗃 Get composer cache directory'
      if: ${{ inputs.use-php == 'true' }}
      id: composer-cache
      shell: bash
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: '💽 Cache composer dependencies'
      if: ${{ inputs.use-php == 'true' }}
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: "${{ runner.os }}-${{ github.ref_name }}-composer-${{ hashFiles('**/composer.lock') }}"
        restore-keys: |
          ${{ runner.os }}-${{ github.head_ref || github.ref_name }}-composer
          ${{ runner.os }}-${{ github.base_ref }}-composer
          ${{ runner.os }}-symfony-composer

    - name: '💽 Cache var directory'
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: var/cache
        key: "${{ runner.os }}-${{ github.ref_name }}-var"
        restore-keys: |
          ${{ runner.os }}-${{ github.head_ref || github.ref_name }}-var
          ${{ runner.os }}-${{ github.base_ref }}-var
          ${{ runner.os }}-symfony-var

    - name: '📦 Install composer dependencies'
      if: ${{ inputs.use-php == 'true' }}
      shell: bash
      run: composer i --no-progress --no-scripts -qn --ansi;

    - name: '🟧 Setup pnpm'
      if: ${{ inputs.use-node == 'true' }}
      uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

    - name: '❇️ Setup Node.js ${{ inputs.node }}'
      if: ${{ inputs.use-node == 'true' }}
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        cache: pnpm
        node-version: ${{ inputs.node }}

    - name: '📦 Install pnpm dependencies'
      if: ${{ inputs.use-node == 'true' }}
      shell: bash
      run: pnpm i -sD --frozen-lockfile --color=always

    - name: '⚜️ Set up Symfony'
      if: ${{ inputs.use-php == 'true' }}
      shell: bash
      run: |
        cp .env.example .env
        APP_DEBUG=1 php bin/console cache:warmup -q
