name: '⚙️ Setup environment'
description: 'Setups environment for validation tasks.'

inputs:
  node:
    description: 'Node.js version to install'
    required: true
    default: '26.x'

runs:
  using: composite
  steps:
    - name: '📋 Install Task'
      shell: bash
      run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

    - name: '🟧 Setup pnpm'
      uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10

    - name: '❇️ Setup Node.js ${{ inputs.node }}'
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        cache: pnpm
        node-version: ${{ inputs.node }}

    - name: '📦 Install pnpm dependencies'
      shell: bash
      run: pnpm install --prefer-offline --color=always
