name: '⚙️ Setup environment'
description: 'Setups environment for validation tasks.'

inputs:
  node:
    description: 'Node.js version to install'
    required: true
    default: '26.x'

runs:
  using: composite
  steps:
    - name: '📋 Install Task'
      uses: go-task/setup-task@a00fbb05ce67b35648be3c78cbc9fd85354c757e # v2.2.0

    - name: '🟧 Setup pnpm & Node.js ${{ inputs.node }}'
      uses: pnpm/setup@703c52620218391530e48b9e8870d5c0082e1b9b # v2.1.0
      with:
        runtime: node@${{ inputs.node }}
        require-lockfile: true
        cache: true
        install: true
