languages:
  - title: English
    enabled: true
    languageId: 0
    base: /
    locale: en_US
    navigationTitle: English
    flag: us
    hreflang: ''
    websiteTitle: ''
    solr_core_read: 'core_en'
