paths:
  - ext/*/Configuration/TSconfig
  - ext/*/Configuration/TypoScript

filePatterns:
  - '*.typoscript'

sniffs:
  - class: Indentation
    parameters:
      useSpaces: true
      indentPerLevel: 2
      indentConditions: true
  - class: DeadCode
  - class: OperatorWhitespace
  - class: RepeatingRValue
    disabled: true
  - class: DuplicateAssignment
  - class: EmptySection
    disabled: true
  - class: NestingConsistency
    parameters:
      commonPathPrefixThreshold: 1
