services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - 8080
      - 8443
    env_file:
      - .env
    environment:
      APP_ENV: dev
      APP_SECRET: ${APP_SECRET}
      PHP_OPCACHE_ENABLE: "0"
      AUTORUN_ENABLED: "false"
      APP_RUNTIME_OPTIONS: '{"disable_dotenv":true}'
      DEFAULT_URI: ${DEFAULT_URI}
      DATABASE_URL: mysql://notes:${DB_PASSWORD}@db:3306/symfony?serverVersion=mariadb-11.8.1&charset=utf8mb4
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal
      - dokploy-network

  db:
    image: mariadb:11.8
    restart: unless-stopped
    environment:
      MARIADB_USER: notes
      MARIADB_DATABASE: symfony
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    expose:
      - 3306
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - internal
      - dokploy-network

volumes:
  db_data:

networks:
  internal:
    driver: bridge
  dokploy-network:
    external: true
