services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Typo3Notes\NtsSite\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  # Disable "Help Toolbar Item"
  TYPO3\CMS\Backend\Backend\ToolbarItems\HelpToolbarItem:
    autoconfigure: false
