name: typo3
type: typo3
docroot: web
database:
  type: mariadb
  version: '10.11'
php_version: '8.3'
nodejs_version: '20'
webserver_type: nginx-fpm
xdebug_enabled: false
web_environment:
  - 'TYPO3_CONTEXT=Development/DDEV'
hooks:
  pre-start:
    # Add task to ddev if not already installed.
    - exec-host: |
        ddev get --installed | grep -q 'gebruederheitz/ddev-taskfile' || ddev get gebruederheitz/ddev-taskfile &>/dev/null
