name: notes
type: generic
webserver_type: generic
nodejs_version: '22'
corepack_enable: true
omit_containers: [db]
disable_upload_dirs_warning: true
web_extra_exposed_ports:
  - name: vitepress
    container_port: 5173
    http_port: 80
    https_port: 443
  - name: vitepress-preview
    container_port: 4173
    http_port: 4172
    https_port: 4173
hooks:
  pre-start:
    # Add pnpm and task to ddev if not already installed.
    - exec-host: |
        ddev add-on list --installed | grep -q 'envsa/ddev-pnpm' || ddev add-on get envsa/ddev-pnpm > /dev/null
        ddev add-on list --installed | grep -q 'gebruederheitz/ddev-taskfile' || ddev add-on get gebruederheitz/ddev-taskfile > /dev/null
  post-start:
    - exec: pnpm i
