name: symfony
type: php
docroot: public
database:
  type: mariadb
  version: '11.8'
php_version: '8.5'
host_db_port: '54374'
nodejs_version: '24'
webserver_type: nginx-fpm
xdebug_enabled: false
corepack_enable: true
hooks:
  pre-start:
    # Add pnpm and task to ddev if not already installed.
    - exec-host: |
        ddev add-on list --installed | grep -q 'envsa/ddev-pnpm' || ddev add-on get envsa/ddev-pnpm > /dev/null
        ddev add-on list --installed | grep -q 'gebruederheitz/ddev-taskfile' || ddev add-on get gebruederheitz/ddev-taskfile > /dev/null
  post-start:
    - composer: install
    - exec: pnpm i
