name: typo3
type: typo3
docroot: web
database:
  type: mariadb
  version: '10.11'
php_version: '8.3'
host_db_port: '17903'
nodejs_version: '20'
webserver_type: nginx-fpm
xdebug_enabled: false
web_environment:
  - 'TYPO3_CONTEXT=Development/DDEV'
  - 'SOLR_SCHEME=http'
  - 'SOLR_HOST=typo3-solr'
  - 'SOLR_PORT=8983'
hooks:
  pre-start:
    # Add pnpm, task and solr to ddev if not already installed.
    - exec-host: |
        ddev get --installed | grep -q 'envsa/ddev-pnpm' || ddev get envsa/ddev-pnpm &>/dev/null
        ddev get --installed | grep -q 'gebruederheitz/ddev-taskfile' || ddev get gebruederheitz/ddev-taskfile &>/dev/null
        ddev get --installed | grep -q 'ddev/ddev-typo3-solr' || ddev get ddev/ddev-typo3-solr &>/dev/null
  post-start:
    - composer: install
    - exec-host: ddev solrctl apply
