name: '🚀 CD | ⚡️ VitePress'

on:
  push:
    branches:
      - gh-pages
    paths-ignore:
      - README.md
      - LICENSE.md

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions: {}

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  cleanup:
    name: '🧹 Clean up GitHub repo'
    runs-on: ubuntu-latest
    permissions:
      actions: write
      deployments: write

    steps:
      - name: '🗑 Delete deployment'
        uses: strumwolf/delete-deployment-environment@035f6d27c8b8951729f4d71b2d3d6a7975139476 # v4.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: github-pages
          onlyRemoveDeployments: true

      - name: '🗑 Delete workflow runs'
        uses: dmvict/clean-workflow-runs@767ab3d12f7880826d993451f264ddc8036c9941 # v1.2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          save_period: 7
          save_min_runs_number: 1
          branch: gh-pages

  build:
    name: '🏗️ Build'
    needs: cleanup
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: '🛎️ Checkout'
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: '⚙️ Prepare environment'
        uses: ./.github/actions/setup-environment

      - name: '⚡️ Build site with VitePress'
        run: task build
        env:
          VITE_GTAG: ${{ vars.VITE_GTAG }}

      - name: '📤 Upload artifact'
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: ./dist
          name: dist

  deploy:
    name: '🌐 Deploy'
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: '🚀 Deploy to GitHub Pages'
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
        with:
          artifact_name: dist
