name: 🔄 CI | ⚡️ VitePress

on:
  push:
    branches:
      - gh-pages
    paths-ignore:
      - README.md
      - LICENSE.md
  pull_request:
    branches:
      - gh-pages
    paths-ignore:
      - README.md
      - LICENSE.md

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ci
  cancel-in-progress: false

jobs:
  lint:
    name: '🪄 Lint | ${{ matrix.command.name }}'
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        command:
          - { name: '🅿️ Prettier', command: 'lint:prettier' }

    steps:
      - name: '🛎 Checkout'
        uses: actions/checkout@v5

      - name: '⚙️ Prepare environment'
        uses: ./.github/actions/setup-environment

      - name: '${{ matrix.command.name }} validate'
        run: task ${{ matrix.command.command }}

  build:
    name: '🏗️ Build | node - ${{ matrix.node }}'
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node: [22.x, 24.x]

    steps:
      - name: '🛎️ Checkout'
        uses: actions/checkout@v5

      - name: '⚙️ Prepare environment'
        uses: ./.github/actions/setup-environment
        with:
          node: ${{ matrix.node }}

      - name: '⚡️ Build site with VitePress'
        run: task build
