name: '🔄 CI | 🧰 Laravel'

on:
  push:
    branches:
      - laravel
    paths-ignore:
      - README.md
      - LICENSE.md
  pull_request:
    branches:
      - laravel
    paths-ignore:
      - README.md
      - LICENSE.md

  # Allows running this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  cleanup:
    name: '🧹 Clean up GitHub repo'
    runs-on: ubuntu-latest
    permissions: write-all
    if: github.event_name != 'pull_request'

    steps:
      - name: '🗑 Delete workflow runs'
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 7
          keep_minimum_runs: 1
          delete_workflow_pattern: ci-laravel.yml

  lint:
    name: '🪄 Lint | ${{ matrix.command.name }}'
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        command:
          - {
              name: '📦 Composer',
              command: 'lint:composer',
              php: true,
            }
          - {
              name: '🧽 Pint',
              command: 'lint:pint -- --format=checkstyle | tail -n +2 | cs2pr',
              php: true,
            }
          - {
              name: '🅿️ Prettier',
              command: 'lint:prettier',
              node: true,
            }
          - {
              name: '🏠 Rector',
              command: 'lint:rector -- --no-progress-bar --output-format=github',
              php: true,
            }

    steps:
      - name: '🛎 Checkout'
        uses: actions/checkout@v6

      - name: '⚙️ Prepare environment'
        uses: ./.github/actions/setup-validation
        with:
          use-php: ${{ matrix.command.php }}
          use-node: ${{ matrix.command.node }}

      - name: '${{ matrix.command.name }} validate'
        run: task ${{ matrix.command.command }}

  lint_phpstan:
    name: '🪄 Lint | 🔍 PHPStan'
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:18
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: db
          POSTGRES_USER: db
          POSTGRES_PASSWORD: db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: '🛎 Checkout'
        uses: actions/checkout@v5

      - name: '⚙️ Prepare environment'
        uses: ./.github/actions/setup-validation
        with:
          use-php: true
          use-db: true

      - name: '🔍 PHPStan validate'
        run: task lint:phpstan -- --no-progress
        env:
          DB_HOST: 127.0.0.1
          DB_DATABASE: db
          DB_USERNAME: db
          DB_PASSWORD: db

  test:
    name: '♻️ Test | ${{ matrix.command.name }}'
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: testing
          POSTGRES_USER: db
          POSTGRES_PASSWORD: db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      fail-fast: false
      matrix:
        command:
          - { name: '🧮 Coverage', command: 'test:coverage -- --ci', report: false }
          - { name: '🧬 Feature',  command: 'test:feature -- --ci',  report: true  }
          - { name: '🔬 Unit',     command: 'test:unit -- --ci',     report: true  }
          - { name: '🦠 Mutate',   command: 'test:mutate -- --ci',   report: false }

    steps:
      - name: '🛎 Checkout'
        uses: actions/checkout@v5

      - name: '⚙️ Prepare environment'
        uses: ./.github/actions/setup-testing

      - name: '${{ matrix.command.name }} tests'
        run: task ${{ matrix.command.command }}
        env:
          DB_HOST: 127.0.0.1
          DB_DATABASE: testing
          DB_USERNAME: db
          DB_PASSWORD: db

      - name: '☂️ Upload results to Codecov'
        uses: codecov/codecov-action@v5
        if: ${{ matrix.command.report }}
        with:
          slug: maks-oleksyuk/notes
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: ${{ matrix.command.name }}
          directory: ./var/report

      - name: '☂️ Upload test results to Codecov'
        uses: codecov/codecov-action@v5
        if: ${{ matrix.command.report }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: ${{ matrix.command.name }}
          directory: ./var/report
          report_type: test_results
