name: '🔄 CI | 🔳 Next.js'

on:
  push:
    branches:
      - next-js
    paths-ignore:
      - README.md
      - LICENSE.md
  pull_request:
    branches:
      - next-js
    paths-ignore:
      - README.md
      - LICENSE.md

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ci
  cancel-in-progress: false

jobs:
  cleanup:
    name: '🧹 Clean up GitHub repo'
    runs-on: ubuntu-latest
    permissions: write-all
    if: github.event_name != 'pull_request'

    steps:
      - name: '🗑 Delete workflow runs'
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 7
          keep_minimum_runs: 1
          delete_workflow_pattern: ci-next-js.yml

  lint:
    name: '🪄 Lint | ${{ matrix.command.name }}'
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        command:
          - { name: '🗜 TS Types', command: 'lint:type' }
          - { name: '🫐 Biome', command: 'lint:biome -- --reporter=github' }

    steps:
      - name: '🛎 Checkout'
        uses: actions/checkout@v6

      - name: '⚙️ Prepare environment'
        uses: ./.github/actions/setup-environment

      - name: '${{ matrix.command.name }} validate'
        run: task ${{ matrix.command.command }}

  test:
    name: '🧪 Test'
    runs-on: ubuntu-latest

    steps:
      - name: '🛎 Checkout'
        uses: actions/checkout@v6

      - name: '⚙️ Prepare environment'
        uses: ./.github/actions/setup-environment

      - name: '🧪 Run test suite'
        run: task test
